version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run
          #start: npm start
  nightly:
    triggers:
      - schedule:
          #https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow
          #https://crontab.guru/#0_0_*_*_*
          cron: "5 * * * 1,2,3,4,5,6"
          filters:
            branches:
              only: master
    jobs:
      - cypress/run